### ISSUE TITLE
initial development feedback

### ISSUE THREAD

**Issue by betaboon** [betaboon/philips-airpurifier#1]
This issue is the place to give me feedback on the initial implementation

**Comment by tunip** [comment]
First, thanks for your variant of custom implementation.

I have a ac2889/10 air purifier and could use it with your implementation.

<img width="404" alt="Bildschirmfoto 2020-12-22 um 19 58 23" src="https://user-images.githubusercontent.com/11404472/102923582-46477680-4490-11eb-92c3-ac3029ab612b.png">

Is in the future planed to also control (mode, speed) the air purifier?

**Comment by tunip** [comment]
Also have to change from `platform: philips-airpurifier` to `platform: philips_airpurifier`. Otherwise the platform is unknown.

**Comment by tunip** [comment]
After 1 hour test run, can't switch off the air purifier anymore (switch in HA goes back to ON).

**Comment by betaboon** [comment]
@tunip I'm planning on implementing the control-parts in the next couple of days.
i just noticed the same thing with turn-on/off not working anymore after a while. I'm trying to figure out why right now.

if you want you could provide me with some debug-logs.
adding this to your `configuration.yaml`:
```
logger:
  logs:
    custom_components.philips_airpurifier: debug
```

**Comment by betaboon** [comment]
@tunip i just pushed some changes:
- setting speed now works (but I'm not completely sure if AC4236 and AC2889 are fully compatible in this regard)
- i reworked the device-attribues
- turning on/off after some hours might now be fixed. i will check back tomorrow.

**Comment by spider7611** [comment]
My 4000i "working" only with this: https://github.com/shexbeer/philips-airpurifier trayed all of fork.
When I uninstalled it and installed yours in HACS and restart HA not show up philips fan at all. 
Install back shexbeer fork and "working", but only on and off switch. Not have speed or mode setup. If I switch on or off the purifier manually after in HA not working untill HA restart.

**Comment by tunip** [comment]
Thx, updated to the newest commit. In case of issues I will provide you the needed debug-logs.

**Comment by betaboon** [comment]
@spider7611 did you see in the readme that i changed the platform-string in this integration to `philips_purifier`?

your model is not officially supported by my fork. if you want you can provide me with debug-logs so that i can figure out how to support your device.

**Comment by betaboon** [comment]
@tunip this is kind of expected:
py-air-control and the other integrations do alot of mapping of the `mode` and `om` field in order to determine the speed of the device. as the several models seem to use different values for `mode` and `om` i decided against a fit-all implementation and opted to implement each model individually (eg. your model seems to use `mode=A` for "Auto-mode" while mine uses `mode=AG` for "Auto-mode".)

you could assist me by providing me a debug-log of switching all available modes and speeds in the app.

**Comment by wolfhond** [comment]
Hello,

I have the ac1214/10 this model I can't add. Is there a way that it could work. I have add the log but I cant restart because of this:
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420
Integration: Hass.io (documentation, issues)
First occurred: 15:03:44 (2 occurrences)
Last logged: 15:06:03

Invalid config for [fan.philips_airpurifier]: value is not allowed for dictionary value @ data['model']. Got 'ac1214'. (See ?, line ?).

**Comment by betaboon** [comment]
@wolfhond that model is currently not supported.

@wolfhond @tunip @spider7611 i just pushed some tooling and documentation (in `README.md`) on how to help get your model supported

**Comment by spider7611** [comment]
> @spider7611 did you see in the readme that i changed the platform-string in this integration to `philips_purifier`?
> 
> your model is not officially supported by my fork. if you want you can provide me with debug-logs so that i can figure out how to support your device.

This was the problem: philips**_**purifier
But not working.
Tomorrow if I have time will do the debug. Thank Your Help!

**Comment by spider7611** [comment]
> > @spider7611 did you see in the readme that i changed the platform-string in this integration to `philips_purifier`?
> > your model is not officially supported by my fork. if you want you can provide me with debug-logs so that i can figure out how to support your device.
> 
> This was the problem: philips**_**purifier
> But not working.
> Tomorrow if I have time will do the debug. Thank Your Help!

spider2@ubuntu:~$ cd philips-airpurifier
spider2@ubuntu:~/philips-airpurifier$ source aioairctrl-shell.sh
Requirement already satisfied: pycryptodomex in ./.venv/lib/python3.8/site-packages (3.9.9)
Requirement already satisfied: aiocoap==0.4b3 in ./.venv/lib/python3.8/site-packages (0.4b3)
(.venv) spider2@ubuntu:~/philips-airpurifier$ aioairctrl --host $192.168.1.102 status --json

and nothing happening. When I change mode or speed with the philips app. :(

**Comment by betaboon** [comment]
@spider7611 
> (.venv) spider2@ubuntu:~/philips-airpurifier$ aioairctrl --host $192.168.1.102 status --json

That should have been: `aioairctrl --host 192.168.1.102 status --json`

**Comment by bboerendans** [comment]
> Hello,
> 
> I have the ac1214/10 this model I can't add. Is there a way that it could work. I have add the log but I cant restart because of this:
> Logger: homeassistant.components.hassio
> Source: components/hassio/**init**.py:420
> Integration: Hass.io (documentation, issues)
> First occurred: 15:03:44 (2 occurrences)
> Last logged: 15:06:03
> 
> Invalid config for [fan.philips_airpurifier]: value is not allowed for dictionary value @ data['model']. Got 'ac1214'. (See ?, line ?).

I'm using the same model and here its working. 

I had to remove the other airpurifier hacs plugin + remove the fan: component from configration.yaml. Thereafter rebooted HA, installed this repo, rebooted HA, added the information in configuration as described at Usage:, rebooted again and its working :)

**Comment by spider7611** [comment]
> aioairctrl --host 192.168.1.102 status --json

Here it is:

(.venv) spider2@ubuntu:~/philips-airpurifier$ aioairctrl --host 192.168.1.102 status --json
{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "0", "pwr": "0", "cl": false, "aqil": 100, "uil": "1", "uaset": "A", "mode": "AG", "pm25": 35, "iaql": 6, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 24654929, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
(.venv) spider2@ubuntu:~/philips-airpurifier$ aioairctrl --host 192.168.1.102 status --json
{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "2", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "A", "mode": "AG", "pm25": 28, "iaql": 5, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 24715465, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
(.venv) spider2@ubuntu:~/philips-airpurifier$ aioairctrl --host 192.168.1.102 status --json
{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "t", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "A", "mode": "T", "pm25": 27, "iaql": 5, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 24732432, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
(.venv) spider2@ubuntu:~/philips-airpurifier$ aioairctrl --host 192.168.1.102 status --json
{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "s", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "A", "mode": "S", "pm25": 33, "iaql": 6, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 24746887, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
(.venv) spider2@ubuntu:~/philips-airpurifier$ aioairctrl --host 192.168.1.102 status --json
{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "s", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "A", "mode": "S", "pm25": 34, "iaql": 6, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 24764273, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}

firs off, then turn on, then changed mode

**Comment by betaboon** [comment]
@spider7611 what app-settings do the individual status-data correspond to?
is reading and setting speed in homeassistant working fine for you? it seems like it just might


@bboerendans as mentioned in https://github.com/betaboon/philips-airpurifier/issues/1#issuecomment-750263813 this is kind of expected.
you could help us support your model by providing the raw-status-data as described in the `README.md`

**Comment by bboerendans** [comment]
@betaboon sure, i have added the data in #3

**Comment by kongo09** [comment]
Happy to help, I own the AC2729 and the AC2889. Will provide the data later.

**Comment by spider7611** [comment]
> what app-settings do the individual status-data correspond to?
> is reading and setting speed in homeassistant working fine for you? it seems like it just might

When the purifier state off:` {"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "0", "pwr": "0", "cl": false, "aqil": 100, "uil": "1", "uaset": "A", "mode": "S", "pm25": 2, "iaql": 1, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 91829445, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

This after power on on automatic mode: `{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "A", "mode": "AG", "pm25": 6, "iaql": 2, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 91998274, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

Changed to sleep mode: `{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "s", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "A", "mode": "S", "pm25": 5, "iaql": 2, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 92097432, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

Changed to turbo mode: `{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "t", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "A", "mode": "T", "pm25": 5, "iaql": 2, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 92170912, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

screen light turn off: `{"name": "Living Room", "type": "AC3858", "modelid": "AC3858/50", "swversion": "Ms4304", "language": "EN", "DeviceVersion": "3.0.4", "om": "t", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "A", "mode": "T", "pm25": 6, "iaql": 2, "aqit": 10, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 139, "fltsts1": 4176, "fltsts2": 65535, "filna": "AC3036", "filid": "AC30360123456789012", "range": "Mars", "Runtime": 92250845, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "a90161ca13c111e9bc6802024953075e", "DeviceId": "0adc1a12a3d611e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

**Comment by betaboon** [comment]
i just pushed initial support for AC1214, AC2729, AC2889, AC3858.
as i own a AC4236 only, it would be highly appreciated if you could test the integration with your models.

to better organize the further discussion on each models-support i created individual issues.
please use those issues for any further discussion on the individual models.

[closing in favor of individual issues]
