### ISSUE TITLE
AC3059

### ISSUE THREAD

**Issue by mcshosho** [betaboon/philips-airpurifier#10]
- Mode Sleep (fan speed auto)

`{"name": "Puri", "type": "AC3059", "modelid": "AC3059/50", "swversion": "Ms3301", "language": "EN", "DeviceVersion": "3.0.1", "om": "s", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "P", "mode": "S", "pm25": 4, "iaql": 1, "aqit": 4, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 213, "fltsts1": 4704, "fltsts2": 65535, "filna": "0", "filid": "0", "range": "Mars", "Runtime": 569716814, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "bd5f6b3a13c111e9bc6802024953075e", "DeviceId": "0621c3a02b4d11eb98e4265f39f6f516", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

- Mode Auto (fan speed auto)

`{"name": "Puri", "type": "AC3059", "modelid": "AC3059/50", "swversion": "Ms3301", "language": "EN", "DeviceVersion": "3.0.1", "om": "s", "pwr": "1", "cl": false, "aqil": 10, "uil": "1", "uaset": "P", "mode": "AG", "pm25": 2, "iaql": 1, "aqit": 4, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 213, "fltsts1": 4704, "fltsts2": 65535, "filna": "0", "filid": "0", "range": "Mars", "Runtime": 569964618, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "bd5f6b3a13c111e9bc6802024953075e", "DeviceId": "0621c3a02b4d11eb98e4265f39f6f516", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

- Mode Turbo (fan speed auto)

`{"name": "Puri", "type": "AC3059", "modelid": "AC3059/50", "swversion": "Ms3301", "language": "EN", "DeviceVersion": "3.0.1", "om": "t", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "P", "mode": "T", "pm25": 2, "iaql": 1, "aqit": 4, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 213, "fltsts1": 4704, "fltsts2": 65535, "filna": "0", "filid": "0", "range": "Mars", "Runtime": 570090301, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "bd5f6b3a13c111e9bc6802024953075e", "DeviceId": "0621c3a02b4d11eb98e4265f39f6f516", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

- Fan speed 1

`{"name": "Puri", "type": "AC3059", "modelid": "AC3059/50", "swversion": "Ms3301", "language": "EN", "DeviceVersion": "3.0.1", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "P", "mode": "M", "pm25": 2, "iaql": 1, "aqit": 4, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 213, "fltsts1": 4704, "fltsts2": 65535, "filna": "0", "filid": "0", "range": "Mars", "Runtime": 569794051, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "bd5f6b3a13c111e9bc6802024953075e", "DeviceId": "0621c3a02b4d11eb98e4265f39f6f516", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

- Fan speed 2

`{"name": "Puri", "type": "AC3059", "modelid": "AC3059/50", "swversion": "Ms3301", "language": "EN", "DeviceVersion": "3.0.1", "om": "2", "pwr": "1", "cl": false, "aqil": 100, "uil": "1", "uaset": "P", "mode": "M", "pm25": 1, "iaql": 1, "aqit": 4, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 213, "fltsts1": 4704, "fltsts2": 65535, "filna": "0", "filid": "0", "range": "Mars", "Runtime": 569851726, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "bd5f6b3a13c111e9bc6802024953075e", "DeviceId": "0621c3a02b4d11eb98e4265f39f6f516", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

- lights off

`{"name": "Puri", "type": "AC3059", "modelid": "AC3059/50", "swversion": "Ms3301", "language": "EN", "DeviceVersion": "3.0.1", "om": "s", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "uaset": "P", "mode": "AG", "pm25": 1, "iaql": 1, "aqit": 4, "tvoc": 1, "ddp": "1", "rddp": "1", "err": 0, "fltt1": "A3", "fltt2": "none", "fltsts0": 213, "fltsts1": 4704, "fltsts2": 65535, "filna": "0", "filid": "0", "range": "Mars", "Runtime": 570222666, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "bd5f6b3a13c111e9bc6802024953075e", "DeviceId": "0621c3a02b4d11eb98e4265f39f6f516", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

**Comment by betaboon** [comment]
@mcshosho i just pushed initial support for this model, could you please test and report back ?

**Comment by mcshosho** [comment]
Setting the speed and reporting attributes - is working fine. 
One thing I noticed - when the fan is off and HA is restarted - there is a period (7:37 minutes first time, second time 7:05 minutes) when the fan is reported as unavailable. 
If the fan is on and HA is restarted the status is picked up imediatelly (only 4 seconds)

**Comment by betaboon** [comment]
i pushed support for filter-reading today.

i also just pushed services for:
- child lock
- display backlight
- light brightness
- humidifier function
- humidity

it would be great if you could test it :)

**Comment by mcshosho** [comment]
![image](https://user-images.githubusercontent.com/15107043/103223162-4df29980-492e-11eb-9be1-29c42e5b80ab.png)

filter-reading - working fine 
display backlight - working fine to turn on, turn off
child lock - I see that the attribute is changing but nothing is happening on the device - also in "Clean Home" app I don't see this function so most probably this model AC3059 does not have this function 
light brightness - I think this model have only 3 possible values: 0 (turned off), 10 (when on sleep mode), 100 (turned on) - every other value I put into brightness I get full brightness (100) on the device.

**Comment by mcshosho** [comment]
on thing I noticed - no matter what are the values for pm25, volatile compounds or indoor allergen index - the value for air quality index is ALWAYS 4 
look below - pm25 = 78, allergen = 11 (a test with a parfume :) ) and in upper screenshots (where everything was 1 or 2)
![image](https://user-images.githubusercontent.com/15107043/103227494-2522d200-4937-11eb-80c0-36600b09affc.png)

**Comment by betaboon** [comment]
I'm closing this issue as the initial support for this model seems to be working.

if any new issues arise feel free to open new _dedicated_ issues

@mcshosho i noticed the same thing about `air_quality_index` being `4` on my device. seems like that is not realy being used
