### ISSUE TITLE
Update readme with installation instructions

### ISSUE THREAD

**Issue by MJohnson459** [betaboon/philips-airpurifier#14]
Is it possible to update the readme with instructions on how to install this?

Using this thread I installed HACS but only the original vMrVizzy repository is listed.
https://community.home-assistant.io/t/philips-air-purifier/53030/102

**Comment by jazynek** [comment]
Same here

**Comment by riker09** [comment]
Here's how I got on track: https://hacs.xyz/docs/faq/custom_repositories

But it took me about half an hour of intensive reading the documentation. 😅
