### ISSUE TITLE
'version' needs to be included in the manifest since HA 2021.3.1

### ISSUE THREAD

**Issue by kongo09** [betaboon/philips-airpurifier#17]
HA 2021.3.1 now requires that custom integrations have a version in the manifest. Currently, HA throws the following warning in the log:

> No 'version' key in the manifest file for custom integration 'philips_airpurifier'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'philips_airpurifier'

This will lead to problems down the road.

**Comment by ronaldt80** [comment]
just add `"version": "0.1"` in the manifest.json file

**Comment by kongo09** [comment]
https://github.com/betaboon/philips-airpurifier/pull/18
