### ISSUE TITLE
set_speed has been deprecated in fan

### ISSUE THREAD

**Issue by kongo09** [betaboon/philips-airpurifier#19]
The `fan.set_speed` service has been marked deprecated in HA:
https://www.home-assistant.io/integrations/fan/#deprecated-service-fanset_speed

I guess this needs to move to `fan.set_preset_mode`.

**Comment by kongo09** [comment]
@betaboon I know you're busy with other stuff. Unfortunately, I lack the skills to take over from you. Still, your work has been very valuable for many  users of Philips devices and it's sad to see the momentum go. Is there any hope that you return to your work here?

**Comment by betaboon** [comment]
i can free some time to work on this.
PRs are always welcome. reproducable issues as well.
the biggest problem is the multitude of device-models that seem to behave slightly differently and i only have access to one model.

**Comment by kongo09** [comment]
Thanks. I've never done any python, but I can try for some simple PR.

**Comment by spider7611** [comment]
After last HA update can't turn on my Philips Airpurifier at all. :( 
And the entity fan.philips_airpurifier unavailable. Please can you fix this? 
Only this integration worked with my model: ac3858, but now stopped working.

**Comment by riker09** [comment]
> After last HA update can't turn on my Philips Airpurifier at all. :(
> And the entity fan.philips_airpurifier unavailable. Please can you fix this?
> Only this integration worked with my model: ac3858, but now stopped working.
> Get this error in the log: No 'version' key in the manifest file for custom integration 'philips_airpurifier'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'philips_airpurifier'

The "error" is more of a warning that support will be dropped in the future. So the integration should still work. However, I have some issue with my AC2889 as well. After some time it just seems to stop working to the point that no further data like total runtime, remaining filter time, air quality, etc. is submitted. I can still set the device to different speeds, *EXCEPT* `sleep`. I can turn it off, but after a second or two the switch in HA toggles back to the `ON` state.

I haven't had much time to investigate this, but I restarted HA once and it seemed like this made things better for while. Maybe you can give it a try, restart, and see if that (temporarily) fixes things?

**Comment by spider7611** [comment]
This is true, after restart it is working again. Only get the error or warning message.

**Comment by kongo09** [comment]
I've tried my hand at a pull request #18 to solve the warning and keep this integration working.

@riker09 unfortunately, this integration is so far as good as it gets, but not 100% working. @betaboon did his/her best to get it going, but my feeling is, that the Philips implementation is sketchy.

**Comment by betaboon** [comment]
i scheduled in some time to work on this today.
I'll try to get as many things adressed as possible :)

**Comment by betaboon** [comment]
sadly https://github.com/denysdovhan/purifier-card didnt yet migrate to the new fan-model.
i opened an issue there denysdovhan/purifier-card#39

**Comment by riker09** [comment]
> I've tried my hand at a pull request #18 to solve the warning and keep this integration working.
> 
> @riker09 unfortunately, this integration is so far as good as it gets, but not 100% working. @betaboon did his/her best to get it going, but my feeling is, that the Philips implementation is sketchy.


This is very great news. I don't have much free time to spent on improving my home automation system, let alone improving the components that I'm using. So thank you for the PR!

I appreciate the work done by @betaboon and all fellow contributers. I hope that my advise restarting Home Assistant was not taken in any negative way. This was not intended. I know that maintaining any Open Source Project is a lot of work. Especially when you provide something that should be the manufacturers job. So, l summary, thank you for this custom component. 🙂

**Comment by betaboon** [comment]
@riker09 
> I appreciate the work done by @betaboon and all fellow contributers. I hope that my advise restarting Home Assistant was not taken in any negative way. This was not intended.

no offense taken. quite the opposite: It's always welcome that people help eachother

> Especially when you provide something that should be the manufacturers job.

here the issue is two-fold:
i wouldn't expect the manufacturer to provide integrations for every home-automation system.
but i would expect the manufacturer to provide working interfaces to the devices that we buy and _own_.
and that's the biggest issue with the philips airpurifiers: the interfaces are buggy on every model and buggy in different ways on every model :(
