### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by wolfhond** [betaboon/philips-airpurifier#2]
Hello I have don the steps but I get this:
![image](https://user-images.githubusercontent.com/21154913/103077653-772ec500-45d0-11eb-9dad-f41559959df2.png)

**Comment by betaboon** [comment]
i just quickly threw the script together assuming a working python3 installation with the python interpreter being available as `python3` and pip being available as `pip3`

it looks like you are trying to run it on hassos? it might be easier running it on your linux-computer instead.

**Comment by bboerendans** [comment]
I tried it on Debian on Windows Subsystem and got the same errors. I solved this with installing python3 with these commands:

`sudo apt-get install python3`
`sudo apt-get install python3-venv`

**Comment by betaboon** [comment]
closing as i think this is solved.
feel free to open a new issue if the problem arises again
