### ISSUE TITLE
add machine-readable filter-times

### ISSUE THREAD

**Issue by betaboon** [betaboon/philips-airpurifier#21]
we're exposing filter-times as human readable.
multiple users have reported the need for machine-readable filter-times for better integration with automation.

**Comment by betaboon** [comment]
relevant comments from #4

> > > Another question regarding the remaining time for all filters: Currently you convert them to a non standard format which is hard to handle in HA automations. The original remaining time is just hours, which is very handy regarding HA scripting. Is there any reason why you convert them to "166 days, 14:00:00"?
> > 
> > 
> > i chose a representation that is human-readable.
> 
> I understand this, but it is not machine readable which should be in my opinion the priority for a HA integration for a sensor. For the UI (and the human readability) it could be converted via templating. But anyway, this are just my two cents ;)

> I also would like to add to @nicx point on remaining time for filter: making it human readable means it's harder to assign any automations to it (for example: be notified when filter needs change). if you're ok with it, I can try to add new attributes with remaining time in hours instead of human readable.

**Comment by betaboon** [comment]
@nicx @arthurgeek i just released a new version which includes the raw, machine-readable filter-times

**Comment by nicx** [comment]
@betaboon great, thanks a lot!
