### ISSUE TITLE
Raw status data - AC1214/10

### ISSUE THREAD

**Issue by bboerendans** [betaboon/philips-airpurifier#3]
`{"name": "kantoor", "type": "AC1214", "modelid": "AC1214/10", "swversion": "2.0.0", "om": "2", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "N", "pm25": 26, "iaql": 5, "aqit": 10, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 262, "fltsts1": 3924, "fltsts2": 1425, "ota": "no", "Runtime": 26217749, "WifiVersion": "AWS_Philips_AIR@51.1", "ProductId": "dca8c9d2f2ab11e8a1e3061302926720", "DeviceId": "766b1454926511e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}`

**Comment by betaboon** [comment]
could you provide the status-data for each individual mode and speed that you can select in the app?

**Comment by bboerendans** [comment]
Sure, i'm happy to help :)

I opened the app, childlock is disabled:

Fanspeed: Auto
Mode: Auto
{"name": "kantoor", "type": "AC1214", "modelid": "AC1214/10", "swversion": "2.0.0", "om": "2", "pwr": "1", "cl": false, "aqil": 50, "uil": "1", "dt": 0, "dtrs": 0, "mode": "P", "pm25": 14, "iaql": 4, "aqit": 10, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 262, "fltsts1": 3924, "fltsts2": 1425, "ota": "no", "Runtime": 26563697, "WifiVersion": "AWS_Philips_AIR@51.1", "ProductId": "dca8c9d2f2ab11e8a1e3061302926720", "DeviceId": "766b1454926511e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}

Fanspeed: Auto
Mode: Allergen mode
{"name": "kantoor", "type": "AC1214", "modelid": "AC1214/10", "swversion": "2.0.0", "om": "3", "pwr": "1", "cl": false, "aqil": 50, "uil": "1", "dt": 0, "dtrs": 0, "mode": "A", "pm25": 15, "iaql": 4, "aqit": 10, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 262, "fltsts1": 3924, "fltsts2": 1425, "ota": "no", "Runtime": 26616488, "WifiVersion": "AWS_Philips_AIR@51.1", "ProductId": "dca8c9d2f2ab11e8a1e3061302926720", "DeviceId": "766b1454926511e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}

Fanspeed: Auto
Mode: Night detection mode:
{"name": "kantoor", "type": "AC1214", "modelid": "AC1214/10", "swversion": "2.0.0", "om": "t", "pwr": "1", "cl": false, "aqil": 50, "uil": "1", "dt": 0, "dtrs": 0, "mode": "N", "pm25": 16, "iaql": 4, "aqit": 10, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 262, "fltsts1": 3924, "fltsts2": 1425, "ota": "no", "Runtime": 26682955, "WifiVersion": "AWS_Philips_AIR@51.1", "ProductId": "dca8c9d2f2ab11e8a1e3061302926720", "DeviceId": "766b1454926511e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}

Fanspeed: speed 1
{"name": "kantoor", "type": "AC1214", "modelid": "AC1214/10", "swversion": "2.0.0", "om": "1", "pwr": "1", "cl": false, "aqil": 50, "uil": "1", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 13, "iaql": 4, "aqit": 10, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 262, "fltsts1": 3924, "fltsts2": 1425, "ota": "no", "Runtime": 26754298, "WifiVersion": "AWS_Philips_AIR@51.1", "ProductId": "dca8c9d2f2ab11e8a1e3061302926720", "DeviceId": "766b1454926511e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}

Fanspeed: speed 2
{"name": "kantoor", "type": "AC1214", "modelid": "AC1214/10", "swversion": "2.0.0", "om": "2", "pwr": "1", "cl": false, "aqil": 50, "uil": "1", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 15, "iaql": 4, "aqit": 10, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 262, "fltsts1": 3924, "fltsts2": 1425, "ota": "no", "Runtime": 26777352, "WifiVersion": "AWS_Philips_AIR@51.1", "ProductId": "dca8c9d2f2ab11e8a1e3061302926720", "DeviceId": "766b1454926511e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}

Fanspeed: speed 3:
{"name": "kantoor", "type": "AC1214", "modelid": "AC1214/10", "swversion": "2.0.0", "om": "3", "pwr": "1", "cl": false, "aqil": 50, "uil": "1", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 13, "iaql": 4, "aqit": 10, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 262, "fltsts1": 3924, "fltsts2": 1425, "ota": "no", "Runtime": 26820411, "WifiVersion": "AWS_Philips_AIR@51.1", "ProductId": "dca8c9d2f2ab11e8a1e3061302926720", "DeviceId": "766b1454926511e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}

Fanspeed: Turbo
{"name": "kantoor", "type": "AC1214", "modelid": "AC1214/10", "swversion": "2.0.0", "om": "t", "pwr": "1", "cl": false, "aqil": 50, "uil": "1", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 13, "iaql": 4, "aqit": 10, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 262, "fltsts1": 3924, "fltsts2": 1425, "ota": "no", "Runtime": 26842391, "WifiVersion": "AWS_Philips_AIR@51.1", "ProductId": "dca8c9d2f2ab11e8a1e3061302926720", "DeviceId": "766b1454926511e9a1e3061302926720", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}

**Comment by betaboon** [comment]
I'll take a shot at implementing that tomorrow :) thanks for your support.

**Comment by bboerendans** [comment]
Some extra details after checking the raw data and the app:

The filters and days remaining:

fltsts0 = first filter (don't know the correct english word, its the one you have to clear by yourself)
fltsts2 = AC filter
fltsts1 = HEPA filter

**Comment by barbatron** [comment]
> fltsts0 = first filter (don't know the correct english word, its the one you have to clear by yourself)

It's "pre-filter" in [the manual](https://www.download.p4c.philips.com/files/a/ac1214_10/ac1214_10_dfu_ukr.pdf) (page 10)

Thanks for working on this, can't wait! :)

**Comment by wolfhond** [comment]
me too I can't wait 

Mary Christmas ;-)

**Comment by kongo09** [comment]
Here comes my data for the AC2729/10 model.

base setting:

- power: on
- mode: automatic
- child lock: off
- fan: automatic
- 2-1 function: purification only
- time: off
- light: off

```
{
    "name": "Schlafzimmer",
    "type": "AC2729",
    "modelid": "AC2729/10",
    "swversion": "0.2.1",
    "om": "1",
    "pwr": "1",
    "cl": false,
    "aqil": 0,
    "uil": "0",
    "dt": 0,
    "dtrs": 0,
    "mode": "P",
    "func": "P",
    "rhset": 40,
    "rh": 45,
    "temp": 20,
    "pm25": 13,
    "iaql": 4,
    "aqit": 4,
    "ddp": "1",
    "rddp": "1",
    "err": 49408,
    "wl": 0,
    "fltt1": "A3",
    "fltt2": "C7",
    "fltsts0": 62,
    "fltsts1": 3278,
    "fltsts2": 3278,
    "wicksts": 3278,
    "range": "MicroMario",
    "Runtime": 920305068,
    "WifiVersion": "AWS_Philips_AIR@62.1",
    "ProductId": "85bc26fae62611e8a1e3061302926720",
    "DeviceId": "3c84c6c8123311ebb1ae8e3584d00715",
    "StatusType": "localcontrol",
    "ConnectType": "Localcontrol"
}
```

**Comment by kongo09** [comment]
Here comes my data for the AC2889/10 model.

base setting:

- power: on
- mode: automatic
- child lock: off
- fan: automatic
- time: off
- light: on at 100%

Fanspeed: Auto
Mode: Auto
`{"name": "Kinderzimmer", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "1", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "P", "pm25": 15, "iaql": 4, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 52, "fltsts1": 4023, "fltsts2": 1623, "range": "Comfort", "Runtime": 55944870, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "82fa3e40832611ea9d377ae8b5230ac3", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
`

Fanspeed: Auto
Mode: Allergen mode
`{"name": "Kinderzimmer", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "2", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "A", "pm25": 14, "iaql": 4, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 52, "fltsts1": 4023, "fltsts2": 1623, "range": "Comfort", "Runtime": 55984720, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "82fa3e40832611ea9d377ae8b5230ac3", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
`

Fanspeed: Auto
Mode: Bacteria and Viral mode
`{"name": "Kinderzimmer", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "2", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "B", "pm25": 13, "iaql": 4, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 52, "fltsts1": 4023, "fltsts2": 1623, "range": "Comfort", "Runtime": 56029086, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "82fa3e40832611ea9d377ae8b5230ac3", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
`

Fanspeed: sleep
`{"name": "Kinderzimmer", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "s", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 14, "iaql": 4, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 52, "fltsts1": 4023, "fltsts2": 1623, "range": "Comfort", "Runtime": 56104945, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "82fa3e40832611ea9d377ae8b5230ac3", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
`

Fanspeed: speed 1
`{"name": "Kinderzimmer", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "1", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 7, "iaql": 2, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 52, "fltsts1": 4023, "fltsts2": 1623, "range": "Comfort", "Runtime": 56142491, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "82fa3e40832611ea9d377ae8b5230ac3", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
`

Fanspeed: speed 2
`{"name": "Kinderzimmer", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "2", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 6, "iaql": 2, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 52, "fltsts1": 4023, "fltsts2": 1623, "range": "Comfort", "Runtime": 56178011, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "82fa3e40832611ea9d377ae8b5230ac3", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
`

Fanspeed: speed 3
`{"name": "Kinderzimmer", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "3", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 6, "iaql": 2, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 52, "fltsts1": 4023, "fltsts2": 1623, "range": "Comfort", "Runtime": 56219296, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "82fa3e40832611ea9d377ae8b5230ac3", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
`

Fanspeed: Turbo
`{"name": "Kinderzimmer", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "t", "pwr": "1", "cl": false, "aqil": 0, "uil": "0", "dt": 0, "dtrs": 0, "mode": "M", "pm25": 21, "iaql": 5, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 52, "fltsts1": 4023, "fltsts2": 1623, "range": "Comfort", "Runtime": 56242683, "WifiVersion": "AWS_Philips_AIR@62.1", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "82fa3e40832611ea9d377ae8b5230ac3", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
`

I also noticed a difference in the setting of the light:

State | AC2728 | AC2889
Light off |  `"aqil":0, "uil":0` |  `"aqil":0, "uil":0`

**Comment by nicx** [comment]
I could deliver the output of my AC2729/10 but as far as I see @kongo09 already did that :)

**Comment by betaboon** [comment]
i just pushed initial support for AC1214, AC2729, AC2889, AC3858.
as i own a AC4236 only, it would be highly appreciated if you could test the integration with your models.

to better organize the further discussion on each models-support i created individual issues.
please use those issues for any further discussion on the individual models.

[closing in favor of individual issues]
