### ISSUE TITLE
Server cannot connect to the AC2729/10 purifier.

### ISSUE THREAD

**Issue by eliogrin** [betaboon/philips-airpurifier#31]
Hi guys,
Please, can you help with issue which I faces with. I'm trying to add my AC2729/10 device to the home assistant but seems my server cannot reach it. And I cannot see any fan in my system. You can see the log below. HA and Philips in the same wifi network, mobile application working fine. Any ideas what it can be?

> 2021-03-24 19:13:33 WARNING (MainThread) [homeassistant.loader] You are using a custom integration philips_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2021-03-24 19:13:33 INFO (MainThread) [homeassistant.components.fan] Setting up fan.philips_airpurifier
> 2021-03-24 19:13:34 DEBUG (MainThread) [aioairctrl.coap.client] syncing
> 2021-03-24 19:13:36 DEBUG (MainThread) [coap] Sending request - Token: 0b8e, Remote: <UDP6EndpointAddress 192.168.24.51>
> 2021-03-24 19:13:36 DEBUG (MainThread) [coap] Sending message <aiocoap.Message at 0xae2d8310: Type.NON POST (MID 7201, token 0b8e) remote <UDP6EndpointAddress 192.168.24.51>, 1 option(s), 8 byte(s) payload>
> 2021-03-24 19:13:44 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform philips_airpurifier is taking over 10 seconds.
> 2021-03-24 19:14:33 ERROR (MainThread) [homeassistant.components.fan] Setup of platform philips_airpurifier is taking longer than 60 seconds. Startup will proceed without waiting any longer.
> 2021-03-24 19:17:05 ERROR (MainThread) [coap] Connection loss was not expected.

**Comment by kongo09** [comment]
Can you post your configuration yaml?

**Comment by eliogrin** [comment]
> Can you post your configuration yaml?

yes, off course

Here's single line from configuration yaml:
`fan: !include devices/fan.yaml`

and fan.yaml:
```
- platform: philips_airpurifier
  name: Kids Air Purifier
  host: "192.168.24.51"
  model: ac2729
```

Any ideas what it can be?

**Comment by ronaldt80** [comment]
How old is the purifier? Is it a pre 2020 model? If so it might be an http
one. Try another fork, for instance GeorgeSG's fork.

Ronald

**Comment by GSzabados** [comment]
> - platform: philips_airpurifier
>   name: Kids Air Purifier
>   host: "192.168.24.51"
>   model: ac2729

Maybe I am mistaken, but that shouldn't be `philips-airpurifier`    - and not _

**Comment by eliogrin** [comment]
> How old is the purifier? Is it a pre 2020 model? If so it might be an http one. Try another fork, for instance GeorgeSG's fork. Ronald
> […](#)

Thanks for suggestion, I changed plugin and it's start to work. 

@betaboon maybe let's add this information to readme.md? Or you have plan to support HTTP protocol as well?

**Comment by betaboon** [comment]
thank you guys for assisting each other so brilliantly :)

@eliogrin i have no plans of supporting http/other-protocols as there are working implementations for those.
i was considering renaming this integration to something like `philips_airpurifier_coap` to make it more explicit and prevent issues like these.

**Comment by eliogrin** [comment]
@betaboon, thank you for your work to support this devices. I believe it's a good idea, so users will be able to use both integration if they will have few purifiers with different protocols. At least I have plan to buy another one with new protocol. Thanks!
