### ISSUE TITLE
Would it be possible to make this an official HA integration?

### ISSUE THREAD

**Issue by ghost** [betaboon/philips-airpurifier#68]
Also trying with the other forks: Would it be possible to make this an official HA integration? So more people can enjoy this? https://developers.home-assistant.io/
(Just bought an Philips AC3829 because i'm so damn allergic to dust)
Would be great since the purifiers a really a missing gap in HA. :-)

**Comment by kongo09** [comment]
Well, in any case, this would require some more or less permanent maintainers. @betaboon has gone silent some time ago, so we have to assume that (s)he doesn't have time anymore to work on this. Unfortunately, there doesn't seem to be anyone on the horizon with enough Python skills to take over.

**Comment by ghost** [comment]
Ah, oke!
