### ISSUE TITLE
irreliable / devices disconnect and/or show incorrect status

### ISSUE THREAD

**Issue by prankousky** [betaboon/philips-airpurifier#74]
Hi everybody,

first of all, thank you for this project. I bought two philips devices just because it exists:

* AC2889
* AC2939

I have these devices set up according to the documentation. However, there are issues:

# incorrect status

Let's say a device is current `on`; Home Assistant reports it as `off`, but it is `on` in the `CleanHome+` app (I **only** use this app when there are problems, it is normally forbidden wifi access via my rooted android so that it cannot interfere with this integration).

I can then *quickly* turn it on, then off, in Home Assistant, and this will work: the device (which **was** already on) will turn off. This only works when I do it very quickly, before Home Assistant automatically sets it to off. When I then turn it on in Home Assistant, it will actually turn on the device, but will still be set to off in Home Assistant.

# disconnect

This seems to be random. When this happens, it **usually** just happens to one of the two devices, rarely both of them are unavailable *at the same time*. When this happens, I usually do this, then they are available again

1. power off device by unplugging it
2. plugging it back in
3. restarting Home Assistant

Point 3 is what makes this a bit bothering, I wouldn't mind **just** unplugging them and plugging them back in, but a full HASS restart always takes (just a little bit of) time and -depending on what automations might run at the time of the restart- might interfere with automations.

It has been like this for quite some time; I always update both Home Assistant and philips-airpurifier-coap to the newest version as soon as they are available (the latter via HACS).

This has happened when I only had the  AC2889, but it feels like it happens even more frequently now that I added an AC2939. I might be wrong on this because now there is just an additional device to disconnect, so it *feels* like it happens more often.

Has this happened to anybody else? Is there anything I can do to fix it?

Thank you in advance for your help :)

**Comment by kongo09** [comment]
Please take a look at debug logs to see the status which shows what data HA receives.

Overally, this sounds very much like the connectivity problem the Philips devices are plagued with since a firmware update over a year ago. And nobody has found a solution yet.

**Comment by kongo09** [comment]
You might want to try my iteration of @betaboon  work which is using a new version of `aiocoap` that might or might not help. It also brings a long list of more features: https://github.com/kongo09/philips-airpurifier-coap

**Comment by prankousky** [comment]
Thank you.
